// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#include "ui.h"
#include "ui_helpers.h"
#include "../ui_chart_init.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_Screen_screen_init();
    ui_Monitor_Screen_screen_init();
    ui_Control_Screen_screen_init();
    ui_Settings_Screen_screen_init();    ui_Analysis_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home_Screen);
    
    // Initialize charts for real-time data streaming
    ui_charts_init_realtime();
    
    // Start real-time updates after a short delay to ensure all screens are loaded
    ui_charts_start_realtime();
}

void ui_destroy(void)
{
    // Stop chart updates before destroying UI
    ui_charts_stop_realtime();
    
    ui_Home_Screen_screen_destroy();
    ui_Monitor_Screen_screen_destroy();
    ui_Control_Screen_screen_destroy();
    ui_Settings_Screen_screen_destroy();
    ui_Analysis_Screen_screen_destroy();
}
