// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Display_Test

#include "ui.h"

#include <stdio.h>

void home_btn_clicked(lv_event_t * e)
{
	printf("Home button clicked!\n");
}
