// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#include "../ui.h"

lv_obj_t * ui_Analysis_Screen;
lv_obj_t * ui_Navigation_Bar5;
lv_obj_t * ui_Button27;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Button28;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Button29;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Button30;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Button34;
lv_obj_t * ui_Label48;

// event funtions
void ui_event_Button27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Monitor_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Monitor_Screen_screen_init);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Control_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Control_Screen_screen_init);
    }
}

void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_btn_clicked(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Screen_screen_init);
    }
}

void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Analysis_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Analysis_Screen_screen_init);
    }
}

void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_Screen_screen_init);
    }
}

// build funtions

void ui_Analysis_Screen_screen_init(void)
{
    ui_Analysis_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Analysis_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Navigation_Bar5 = lv_obj_create(ui_Analysis_Screen);
    lv_obj_set_width(ui_Navigation_Bar5, 836);
    lv_obj_set_height(ui_Navigation_Bar5, 55);
    lv_obj_set_x(ui_Navigation_Bar5, 0);
    lv_obj_set_y(ui_Navigation_Bar5, 204);
    lv_obj_set_align(ui_Navigation_Bar5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Navigation_Bar5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Navigation_Bar5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Navigation_Bar5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation_Bar5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation_Bar5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Navigation_Bar5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Navigation_Bar5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_btn_create(ui_Navigation_Bar5);
    lv_obj_set_width(ui_Button27, 125);
    lv_obj_set_height(ui_Button27, 45);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Monitor");

    ui_Button28 = lv_btn_create(ui_Navigation_Bar5);
    lv_obj_set_width(ui_Button28, 125);
    lv_obj_set_height(ui_Button28, 45);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Control");

    ui_Button29 = lv_btn_create(ui_Navigation_Bar5);
    lv_obj_set_width(ui_Button29, 125);
    lv_obj_set_height(ui_Button29, 45);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button29, lv_color_hex(0x20D6F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label42 = lv_label_create(ui_Button29);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Home");

    ui_Button30 = lv_btn_create(ui_Navigation_Bar5);
    lv_obj_set_width(ui_Button30, 125);
    lv_obj_set_height(ui_Button30, 45);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Analyze");

    ui_Button34 = lv_btn_create(ui_Navigation_Bar5);
    lv_obj_set_width(ui_Button34, 125);
    lv_obj_set_height(ui_Button34, 45);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "Settings");

    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);

}

void ui_Analysis_Screen_screen_destroy(void)
{
    if(ui_Analysis_Screen) lv_obj_del(ui_Analysis_Screen);

    // NULL screen variables
    ui_Analysis_Screen = NULL;
    ui_Navigation_Bar5 = NULL;
    ui_Button27 = NULL;
    ui_Label40 = NULL;
    ui_Button28 = NULL;
    ui_Label41 = NULL;
    ui_Button29 = NULL;
    ui_Label42 = NULL;
    ui_Button30 = NULL;
    ui_Label43 = NULL;
    ui_Button34 = NULL;
    ui_Label48 = NULL;

}
