// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#ifndef UI_ANALYSIS_SCREEN_H
#define UI_ANALYSIS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Analysis_Screen
extern void ui_Analysis_Screen_screen_init(void);
extern void ui_Analysis_Screen_screen_destroy(void);
extern lv_obj_t * ui_Analysis_Screen;
extern lv_obj_t * ui_Navigation_Bar5;
extern void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label40;
extern void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label41;
extern void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label42;
extern void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label43;
extern void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label48;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

