// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#include "../ui.h"

lv_obj_t * ui_Control_Screen;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Button14;
lv_obj_t * ui_PWM_Label;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Button31;
lv_obj_t * ui_PWM_Label1;
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Button32;
lv_obj_t * ui_PWM_Label2;
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Button33;
lv_obj_t * ui_PWM_Label3;
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Control_Header;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Chart5;
lv_obj_t * ui_Chart6;
lv_obj_t * ui_Navigation_Bar3;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label34;

// event funtions
void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Monitor_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Monitor_Screen_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Control_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Control_Screen_screen_init);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_btn_clicked(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Screen_screen_init);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Analysis_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Analysis_Screen_screen_init);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_Screen_screen_init);
    }
}

// build funtions

void ui_Control_Screen_screen_init(void)
{
    ui_Control_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Control_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Control_Screen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 730);
    lv_obj_set_height(ui_Container3, 300);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 22);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel1, 686);
    lv_obj_set_height(ui_Panel1, 46);
    lv_obj_set_x(ui_Panel1, 30);
    lv_obj_set_y(ui_Panel1, 79);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Relay 1");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -379);
    lv_obj_set_y(ui_Switch2, -89);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Button14 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_Button14, 66);
    lv_obj_set_height(ui_Button14, 28);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWM_Label = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_PWM_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWM_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWM_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWM_Label, "PWM");

    ui_Slider2 = lv_slider_create(ui_Panel1);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, -108);
    lv_obj_set_y(ui_Slider2, -124);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    ui_Panel7 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel7, 686);
    lv_obj_set_height(ui_Panel7, 46);
    lv_obj_set_x(ui_Panel7, 30);
    lv_obj_set_y(ui_Panel7, 79);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "Relay 2");
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, -379);
    lv_obj_set_y(ui_Switch3, -89);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_Button31 = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_Button31, 66);
    lv_obj_set_height(ui_Button31, 28);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWM_Label1 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_PWM_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWM_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWM_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWM_Label1, "PWM");

    ui_Slider3 = lv_slider_create(ui_Panel7);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 150);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, -108);
    lv_obj_set_y(ui_Slider3, -124);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);

    ui_Panel8 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel8, 686);
    lv_obj_set_height(ui_Panel8, 46);
    lv_obj_set_x(ui_Panel8, 30);
    lv_obj_set_y(ui_Panel8, 79);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label45 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "Relay 3");
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, -379);
    lv_obj_set_y(ui_Switch4, -89);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    ui_Button32 = lv_btn_create(ui_Panel8);
    lv_obj_set_width(ui_Button32, 66);
    lv_obj_set_height(ui_Button32, 28);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWM_Label2 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_PWM_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWM_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWM_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWM_Label2, "PWM");

    ui_Slider4 = lv_slider_create(ui_Panel8);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 150);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, -108);
    lv_obj_set_y(ui_Slider4, -124);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);

    ui_Panel9 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel9, 686);
    lv_obj_set_height(ui_Panel9, 46);
    lv_obj_set_x(ui_Panel9, 30);
    lv_obj_set_y(ui_Panel9, 79);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label46 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "Relay 4");
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, -379);
    lv_obj_set_y(ui_Switch5, -89);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);

    ui_Button33 = lv_btn_create(ui_Panel9);
    lv_obj_set_width(ui_Button33, 66);
    lv_obj_set_height(ui_Button33, 28);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWM_Label3 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_PWM_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWM_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWM_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWM_Label3, "PWM");

    ui_Slider5 = lv_slider_create(ui_Panel9);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 150);
    lv_obj_set_height(ui_Slider5, 10);
    lv_obj_set_x(ui_Slider5, -108);
    lv_obj_set_y(ui_Slider5, -124);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);

    ui_Control_Header = lv_obj_create(ui_Control_Screen);
    lv_obj_set_width(ui_Control_Header, 242);
    lv_obj_set_height(ui_Control_Header, 50);
    lv_obj_set_x(ui_Control_Header, 0);
    lv_obj_set_y(ui_Control_Header, -198);
    lv_obj_set_align(ui_Control_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Control_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label47 = lv_label_create(ui_Control_Header);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Control");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart5 = lv_chart_create(ui_Control_Screen);
    lv_obj_set_width(ui_Chart5, 170);
    lv_obj_set_height(ui_Chart5, 76);
    lv_obj_set_x(ui_Chart5, -260);
    lv_obj_set_y(ui_Chart5, -185);
    lv_obj_set_align(ui_Chart5, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart5, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    // Chart data will be managed by chart_data_manager - no static arrays needed

    ui_Chart6 = lv_chart_create(ui_Control_Screen);
    lv_obj_set_width(ui_Chart6, 170);
    lv_obj_set_height(ui_Chart6, 76);
    lv_obj_set_x(ui_Chart6, 260);
    lv_obj_set_y(ui_Chart6, -185);
    lv_obj_set_align(ui_Chart6, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart6, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart6, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    // Chart data will be managed by chart_data_manager - no static arrays needed

    ui_Navigation_Bar3 = lv_obj_create(ui_Control_Screen);
    lv_obj_set_width(ui_Navigation_Bar3, 836);
    lv_obj_set_height(ui_Navigation_Bar3, 55);
    lv_obj_set_x(ui_Navigation_Bar3, 0);
    lv_obj_set_y(ui_Navigation_Bar3, 204);
    lv_obj_set_align(ui_Navigation_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Navigation_Bar3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Navigation_Bar3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Navigation_Bar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation_Bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Navigation_Bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Navigation_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_Navigation_Bar3);
    lv_obj_set_width(ui_Button17, 125);
    lv_obj_set_height(ui_Button17, 45);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Monitor");

    ui_Button18 = lv_btn_create(ui_Navigation_Bar3);
    lv_obj_set_width(ui_Button18, 125);
    lv_obj_set_height(ui_Button18, 45);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Control");

    ui_Button19 = lv_btn_create(ui_Navigation_Bar3);
    lv_obj_set_width(ui_Button19, 125);
    lv_obj_set_height(ui_Button19, 45);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0x20D6F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label32 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Home");

    ui_Button20 = lv_btn_create(ui_Navigation_Bar3);
    lv_obj_set_width(ui_Button20, 125);
    lv_obj_set_height(ui_Button20, 45);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Analyze");

    ui_Button21 = lv_btn_create(ui_Navigation_Bar3);
    lv_obj_set_width(ui_Button21, 125);
    lv_obj_set_height(ui_Button21, 45);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Settings");

    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);

}

void ui_Control_Screen_screen_destroy(void)
{
    if(ui_Control_Screen) lv_obj_del(ui_Control_Screen);

    // NULL screen variables
    ui_Control_Screen = NULL;
    ui_Container3 = NULL;
    ui_Panel1 = NULL;
    ui_Label27 = NULL;
    ui_Switch2 = NULL;
    ui_Button14 = NULL;
    ui_PWM_Label = NULL;
    ui_Slider2 = NULL;
    ui_Panel7 = NULL;
    ui_Label44 = NULL;
    ui_Switch3 = NULL;
    ui_Button31 = NULL;
    ui_PWM_Label1 = NULL;
    ui_Slider3 = NULL;
    ui_Panel8 = NULL;
    ui_Label45 = NULL;
    ui_Switch4 = NULL;
    ui_Button32 = NULL;
    ui_PWM_Label2 = NULL;
    ui_Slider4 = NULL;
    ui_Panel9 = NULL;
    ui_Label46 = NULL;
    ui_Switch5 = NULL;
    ui_Button33 = NULL;
    ui_PWM_Label3 = NULL;
    ui_Slider5 = NULL;
    ui_Control_Header = NULL;
    ui_Label47 = NULL;
    ui_Chart5 = NULL;
    ui_Chart6 = NULL;
    ui_Navigation_Bar3 = NULL;
    ui_Button17 = NULL;
    ui_Label30 = NULL;
    ui_Button18 = NULL;
    ui_Label31 = NULL;
    ui_Button19 = NULL;
    ui_Label32 = NULL;
    ui_Button20 = NULL;
    ui_Label33 = NULL;
    ui_Button21 = NULL;
    ui_Label34 = NULL;

}
