// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#ifndef UI_CONTROL_SCREEN_H
#define UI_CONTROL_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Control_Screen
extern void ui_Control_Screen_screen_init(void);
extern void ui_Control_Screen_screen_destroy(void);
extern lv_obj_t * ui_Control_Screen;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_PWM_Label;
extern lv_obj_t * ui_relay1slider;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_PWM_Label1;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Switch4;
extern void ui_event_Button32(lv_event_t * e);
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_PWM_Label2;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_PWM_Label3;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Control_Header;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Chart5;
extern lv_obj_t * ui_Chart6;
extern lv_obj_t * ui_Navigation_Bar3;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label30;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label31;
extern void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label32;
extern void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label33;
extern void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

