// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#ifndef UI_HOME_SCREEN_H
#define UI_HOME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Screen
extern void ui_Home_Screen_screen_init(void);
extern void ui_Home_Screen_screen_destroy(void);
extern lv_obj_t * ui_Home_Screen;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Navigation_Bar;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Container4;
extern void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

