// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#ifndef UI_MONITOR_SCREEN_H
#define UI_MONITOR_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Monitor_Screen
extern void ui_Monitor_Screen_screen_init(void);
extern void ui_Monitor_Screen_screen_destroy(void);
extern lv_obj_t * ui_Monitor_Screen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart4;
extern lv_obj_t * ui_Navigation_Bar2;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label53;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label23;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label24;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label25;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

