// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#include "../ui.h"

lv_obj_t * ui_Settings_Screen;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Slider6;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Roller3;
lv_obj_t * ui_Navigation_Bar4;
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Button23;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Button25;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Button26;
lv_obj_t * ui_Label39;

// event funtions
void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Monitor_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Monitor_Screen_screen_init);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Control_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Control_Screen_screen_init);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_btn_clicked(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Screen_screen_init);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Analysis_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Analysis_Screen_screen_init);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_Screen_screen_init);
    }
}

// build funtions

void ui_Settings_Screen_screen_init(void)
{
    ui_Settings_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_Settings_Screen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 728);
    lv_obj_set_height(ui_Container5, 357);
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -30);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel10, 652);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Setting");

    ui_Switch6 = lv_switch_create(ui_Panel10);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);

    ui_Panel11 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel11, 652);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label49 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "Setting");

    ui_Checkbox2 = lv_checkbox_create(ui_Panel11);
    lv_checkbox_set_text(ui_Checkbox2, "");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Panel12 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel12, 652);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label50 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "Setting");

    ui_Dropdown1 = lv_dropdown_create(ui_Panel12);
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Panel13 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel13, 652);
    lv_obj_set_height(ui_Panel13, 50);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label51 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -15);
    lv_obj_set_y(ui_Label51, 30);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "Setting");

    ui_Slider6 = lv_slider_create(ui_Panel13);
    lv_slider_set_value(ui_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 150);
    lv_obj_set_height(ui_Slider6, 10);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);

    ui_Panel14 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Panel14, 652);
    lv_obj_set_height(ui_Panel14, 50);
    lv_obj_set_x(ui_Panel14, 1);
    lv_obj_set_y(ui_Panel14, 0);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel14, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label52 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -15);
    lv_obj_set_y(ui_Label52, 30);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "Setting");

    ui_Roller3 = lv_roller_create(ui_Panel14);
    lv_roller_set_options(ui_Roller3, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller3, 100);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    ui_Navigation_Bar4 = lv_obj_create(ui_Settings_Screen);
    lv_obj_set_width(ui_Navigation_Bar4, 836);
    lv_obj_set_height(ui_Navigation_Bar4, 55);
    lv_obj_set_x(ui_Navigation_Bar4, 0);
    lv_obj_set_y(ui_Navigation_Bar4, 204);
    lv_obj_set_align(ui_Navigation_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Navigation_Bar4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Navigation_Bar4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Navigation_Bar4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation_Bar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Navigation_Bar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Navigation_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button22 = lv_btn_create(ui_Navigation_Bar4);
    lv_obj_set_width(ui_Button22, 125);
    lv_obj_set_height(ui_Button22, 45);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Monitor");

    ui_Button23 = lv_btn_create(ui_Navigation_Bar4);
    lv_obj_set_width(ui_Button23, 125);
    lv_obj_set_height(ui_Button23, 45);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Control");

    ui_Button24 = lv_btn_create(ui_Navigation_Bar4);
    lv_obj_set_width(ui_Button24, 125);
    lv_obj_set_height(ui_Button24, 45);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0x20D6F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label37 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Home");

    ui_Button25 = lv_btn_create(ui_Navigation_Bar4);
    lv_obj_set_width(ui_Button25, 125);
    lv_obj_set_height(ui_Button25, 45);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Analyze");

    ui_Button26 = lv_btn_create(ui_Navigation_Bar4);
    lv_obj_set_width(ui_Button26, 125);
    lv_obj_set_height(ui_Button26, 45);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Settings");

    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);

}

void ui_Settings_Screen_screen_destroy(void)
{
    if(ui_Settings_Screen) lv_obj_del(ui_Settings_Screen);

    // NULL screen variables
    ui_Settings_Screen = NULL;
    ui_Container5 = NULL;
    ui_Panel10 = NULL;
    ui_Label28 = NULL;
    ui_Switch6 = NULL;
    ui_Panel11 = NULL;
    ui_Label49 = NULL;
    ui_Checkbox2 = NULL;
    ui_Panel12 = NULL;
    ui_Label50 = NULL;
    ui_Dropdown1 = NULL;
    ui_Panel13 = NULL;
    ui_Label51 = NULL;
    ui_Slider6 = NULL;
    ui_Panel14 = NULL;
    ui_Label52 = NULL;
    ui_Roller3 = NULL;
    ui_Navigation_Bar4 = NULL;
    ui_Button22 = NULL;
    ui_Label35 = NULL;
    ui_Button23 = NULL;
    ui_Label36 = NULL;
    ui_Button24 = NULL;
    ui_Label37 = NULL;
    ui_Button25 = NULL;
    ui_Label38 = NULL;
    ui_Button26 = NULL;
    ui_Label39 = NULL;

}
