// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Guition-JC8048W550C-Battery-Control-UI-Test

#ifndef UI_SETTINGS_SCREEN_H
#define UI_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings_Screen
extern void ui_Settings_Screen_screen_init(void);
extern void ui_Settings_Screen_screen_destroy(void);
extern lv_obj_t * ui_Settings_Screen;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Navigation_Bar4;
extern void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label35;
extern void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label36;
extern void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label37;
extern void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label38;
extern void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

